# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Cloudstorage' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'cloudrail-si-ios-sdk'
  pod 'Toast-Swift', '~> 2.0.0'

  # Pods for Cloudstorage

end
