// Generated by Apple Swift version 2.3 (swiftlang-800.10.12 clang-800.0.38)
#pragma clang diagnostic push

#if defined(__has_include) && __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <objc/NSObject.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if defined(__has_include) && __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus) || __cplusplus < 201103L
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif

#if defined(__has_attribute) && __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if defined(__has_attribute) && __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if defined(__has_attribute) && __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if defined(__has_attribute) && __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name) enum _name : _type _name; enum SWIFT_ENUM_EXTRA _name : _type
# if defined(__has_feature) && __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME) SWIFT_ENUM(_type, _name)
# endif
#endif
#if defined(__has_feature) && __has_feature(modules)
@import ObjectiveC;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
@class NSInputStream;
@class CRCloudMetaData;
@class NSMutableArray;
@class CRSpaceAllocation;

SWIFT_CLASS("_TtC11CloudrailSI3Box")
@interface Box : NSObject
- (nonnull instancetype)initWithClientId:(NSString * _Nonnull)clientId clientSecret:(NSString * _Nonnull)clientSecret redirectUri:(NSString * _Nonnull)redirectUri state:(NSString * _Nonnull)state OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithClientId:(NSString * _Nonnull)clientId clientSecret:(NSString * _Nonnull)clientSecret OBJC_DESIGNATED_INITIALIZER;
- (NSInputStream * _Nullable)downloadFileWithPath:(NSString * _Nonnull)filePath error:(NSError * _Nullable * _Null_unspecified)error;
- (BOOL)uploadFileToPath:(NSString * _Nonnull)filePath stream:(NSInputStream * _Nonnull)stream size:(long)size overwrite:(BOOL)overwrite error:(NSError * _Nullable * _Null_unspecified)error;
- (BOOL)moveFileFromPath:(NSString * _Nonnull)sourcePath destinationPath:(NSString * _Nonnull)destinationPath error:(NSError * _Nullable * _Null_unspecified)error;
- (BOOL)deleteFileWithPath:(NSString * _Nonnull)filePath error:(NSError * _Nullable * _Null_unspecified)error;
- (BOOL)copyFileFromPath:(NSString * _Nonnull)sourcePath destinationPath:(NSString * _Nonnull)destinationPath error:(NSError * _Nullable * _Null_unspecified)error;
- (BOOL)createFolderWithPath:(NSString * _Nonnull)folderPath error:(NSError * _Nullable * _Null_unspecified)error;
- (CRCloudMetaData * _Nullable)metadataOfFileWithPath:(NSString * _Nonnull)filePath error:(NSError * _Nullable * _Null_unspecified)error;
- (NSMutableArray * _Nullable)childrenOfFolderWithPath:(NSString * _Nonnull)folderPath error:(NSError * _Nullable * _Null_unspecified)error;
- (NSString * _Nullable)userLoginAndReturnError:(NSError * _Nullable * _Null_unspecified)error;
- (NSString * _Nullable)userNameAndReturnError:(NSError * _Nullable * _Null_unspecified)error;
- (NSString * _Nullable)shareLinkForFileWithPath:(NSString * _Nonnull)path error:(NSError * _Nullable * _Null_unspecified)error;
- (CRSpaceAllocation * _Nullable)spaceAllocationAndReturnError:(NSError * _Nullable * _Null_unspecified)error;
- (BOOL)loginAndReturnError:(NSError * _Nullable * _Null_unspecified)error;
- (BOOL)logoutAndReturnError:(NSError * _Nullable * _Null_unspecified)error;
- (NSString * _Nullable)saveAsStringAndReturnError:(NSError * _Nullable * _Null_unspecified)error;
- (BOOL)loadAsString:(NSString * _Nonnull)savedState error:(NSError * _Nullable * _Null_unspecified)error;
- (void)setTarget:(id _Null_unspecified)target;
@end


SWIFT_CLASS("_TtC11CloudrailSI7Dropbox")
@interface Dropbox : NSObject
- (nonnull instancetype)initWithClientId:(NSString * _Nonnull)clientId clientSecret:(NSString * _Nonnull)clientSecret redirectUri:(NSString * _Nonnull)redirectUri state:(NSString * _Nonnull)state OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithClientId:(NSString * _Nonnull)clientId clientSecret:(NSString * _Nonnull)clientSecret OBJC_DESIGNATED_INITIALIZER;
- (NSInputStream * _Nullable)downloadFileWithPath:(NSString * _Nonnull)filePath error:(NSError * _Nullable * _Null_unspecified)error;
- (BOOL)uploadFileToPath:(NSString * _Nonnull)filePath stream:(NSInputStream * _Nonnull)stream size:(long)size overwrite:(BOOL)overwrite error:(NSError * _Nullable * _Null_unspecified)error;
- (BOOL)moveFileFromPath:(NSString * _Nonnull)sourcePath destinationPath:(NSString * _Nonnull)destinationPath error:(NSError * _Nullable * _Null_unspecified)error;
- (BOOL)deleteFileWithPath:(NSString * _Nonnull)filePath error:(NSError * _Nullable * _Null_unspecified)error;
- (BOOL)copyFileFromPath:(NSString * _Nonnull)sourcePath destinationPath:(NSString * _Nonnull)destinationPath error:(NSError * _Nullable * _Null_unspecified)error;
- (BOOL)createFolderWithPath:(NSString * _Nonnull)folderPath error:(NSError * _Nullable * _Null_unspecified)error;
- (CRCloudMetaData * _Nullable)metadataOfFileWithPath:(NSString * _Nonnull)filePath error:(NSError * _Nullable * _Null_unspecified)error;
- (NSMutableArray * _Nullable)childrenOfFolderWithPath:(NSString * _Nonnull)folderPath error:(NSError * _Nullable * _Null_unspecified)error;
- (NSString * _Nullable)userLoginAndReturnError:(NSError * _Nullable * _Null_unspecified)error;
- (NSString * _Nullable)userNameAndReturnError:(NSError * _Nullable * _Null_unspecified)error;
- (NSString * _Nullable)shareLinkForFileWithPath:(NSString * _Nonnull)path error:(NSError * _Nullable * _Null_unspecified)error;
- (CRSpaceAllocation * _Nullable)spaceAllocationAndReturnError:(NSError * _Nullable * _Null_unspecified)error;
- (BOOL)loginAndReturnError:(NSError * _Nullable * _Null_unspecified)error;
- (BOOL)logoutAndReturnError:(NSError * _Nullable * _Null_unspecified)error;
- (NSString * _Nullable)saveAsStringAndReturnError:(NSError * _Nullable * _Null_unspecified)error;
- (BOOL)loadAsString:(NSString * _Nonnull)savedState error:(NSError * _Nullable * _Null_unspecified)error;
- (void)setTarget:(id _Null_unspecified)target;
@end

@class CRDateOfBirth;

SWIFT_CLASS("_TtC11CloudrailSI8Facebook")
@interface Facebook : NSObject
- (nonnull instancetype)initWithClientID:(NSString * _Nonnull)clientID clientSecret:(NSString * _Nonnull)clientSecret redirectUri:(NSString * _Nonnull)redirectUri state:(NSString * _Nonnull)state OBJC_DESIGNATED_INITIALIZER;
- (NSString * _Nullable)identifierAndReturnError:(NSError * _Nullable * _Null_unspecified)error;
- (NSString * _Nullable)fullNameAndReturnError:(NSError * _Nullable * _Null_unspecified)error;
- (NSString * _Nullable)emailAndReturnError:(NSError * _Nullable * _Null_unspecified)error;
- (NSString * _Nullable)genderAndReturnError:(NSError * _Nullable * _Null_unspecified)error;
- (NSString * _Nullable)profileDescriptionAndReturnError:(NSError * _Nullable * _Null_unspecified)error;
- (CRDateOfBirth * _Nullable)dateOfBirthAndReturnError:(NSError * _Nullable * _Null_unspecified)error;
- (NSString * _Nullable)localeAndReturnError:(NSError * _Nullable * _Null_unspecified)error;
- (NSString * _Nullable)pictureURLAndReturnError:(NSError * _Nullable * _Null_unspecified)error;
- (BOOL)loginAndReturnError:(NSError * _Nullable * _Null_unspecified)error;
- (BOOL)logoutAndReturnError:(NSError * _Nullable * _Null_unspecified)error;
- (BOOL)postUpdateWithContent:(NSString * _Nonnull)content error:(NSError * _Nullable * _Null_unspecified)error;
- (NSMutableArray * _Nullable)connectionsAndReturnError:(NSError * _Nullable * _Null_unspecified)error;
- (NSString * _Nullable)saveAsStringAndReturnError:(NSError * _Nullable * _Null_unspecified)error;
- (BOOL)loadAsString:(NSString * _Nonnull)savedState error:(NSError * _Nullable * _Null_unspecified)error;
- (void)setTarget:(id _Null_unspecified)target;
@end


SWIFT_CLASS("_TtC11CloudrailSI10Foursquare")
@interface Foursquare : NSObject
- (nonnull instancetype)initWithClientID:(NSString * _Nonnull)clientID clientSecret:(NSString * _Nonnull)clientSecret OBJC_DESIGNATED_INITIALIZER;
- (NSMutableArray * _Nullable)nearbyPoisWithLatitude:(double)latitude longitude:(double)longitude radius:(NSInteger)radius searchTerm:(NSString * _Nonnull)searchTerm categories:(NSMutableArray * _Nonnull)categories error:(NSError * _Nullable * _Null_unspecified)error;
- (void)setTarget:(id _Null_unspecified)target;
@end


SWIFT_CLASS("_TtC11CloudrailSI6GitHub")
@interface GitHub : NSObject
- (nonnull instancetype)initWithClientId:(NSString * _Nonnull)clientId clientSecret:(NSString * _Nonnull)clientSecret redirectUri:(NSString * _Nonnull)redirectUri state:(NSString * _Nonnull)state OBJC_DESIGNATED_INITIALIZER;
- (NSString * _Nullable)identifierAndReturnError:(NSError * _Nullable * _Null_unspecified)error;
- (NSString * _Nullable)fullNameAndReturnError:(NSError * _Nullable * _Null_unspecified)error;
- (NSString * _Nullable)emailAndReturnError:(NSError * _Nullable * _Null_unspecified)error;
- (NSString * _Nullable)genderAndReturnError:(NSError * _Nullable * _Null_unspecified)error;
- (NSString * _Nullable)profileDescriptionAndReturnError:(NSError * _Nullable * _Null_unspecified)error;
- (CRDateOfBirth * _Nullable)dateOfBirthAndReturnError:(NSError * _Nullable * _Null_unspecified)error;
- (NSString * _Nullable)localeAndReturnError:(NSError * _Nullable * _Null_unspecified)error;
- (NSString * _Nullable)pictureURLAndReturnError:(NSError * _Nullable * _Null_unspecified)error;
- (BOOL)loginAndReturnError:(NSError * _Nullable * _Null_unspecified)error;
- (BOOL)logoutAndReturnError:(NSError * _Nullable * _Null_unspecified)error;
- (NSString * _Nullable)saveAsStringAndReturnError:(NSError * _Nullable * _Null_unspecified)error;
- (BOOL)loadAsString:(NSString * _Nonnull)savedState error:(NSError * _Nullable * _Null_unspecified)error;
- (void)setTarget:(id _Null_unspecified)target;
@end


SWIFT_CLASS("_TtC11CloudrailSI11GoogleDrive")
@interface GoogleDrive : NSObject
- (nonnull instancetype)initWithClientID:(NSString * _Nonnull)clientID clientSecret:(NSString * _Nonnull)clientSecret redirectUri:(NSString * _Nonnull)redirectUri state:(NSString * _Nonnull)state OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithClientId:(NSString * _Nonnull)clientId clientSecret:(NSString * _Nonnull)clientSecret OBJC_DESIGNATED_INITIALIZER;
- (NSInputStream * _Nullable)downloadFileWithPath:(NSString * _Nonnull)filePath error:(NSError * _Nullable * _Null_unspecified)error;
- (BOOL)uploadFileToPath:(NSString * _Nonnull)filePath stream:(NSInputStream * _Nonnull)stream size:(long)size overwrite:(BOOL)overwrite error:(NSError * _Nullable * _Null_unspecified)error;
- (BOOL)moveFileFromPath:(NSString * _Nonnull)sourcePath destinationPath:(NSString * _Nonnull)destinationPath error:(NSError * _Nullable * _Null_unspecified)error;
- (BOOL)deleteFileWithPath:(NSString * _Nonnull)filePath error:(NSError * _Nullable * _Null_unspecified)error;
- (BOOL)copyFileFromPath:(NSString * _Nonnull)sourcePath destinationPath:(NSString * _Nonnull)destinationPath error:(NSError * _Nullable * _Null_unspecified)error;
- (BOOL)createFolderWithPath:(NSString * _Nonnull)folderPath error:(NSError * _Nullable * _Null_unspecified)error;
- (CRCloudMetaData * _Nullable)metadataOfFileWithPath:(NSString * _Nonnull)filePath error:(NSError * _Nullable * _Null_unspecified)error;
- (NSMutableArray * _Nullable)childrenOfFolderWithPath:(NSString * _Nonnull)folderPath error:(NSError * _Nullable * _Null_unspecified)error;
- (NSString * _Nullable)userLoginAndReturnError:(NSError * _Nullable * _Null_unspecified)error;
- (NSString * _Nullable)userNameAndReturnError:(NSError * _Nullable * _Null_unspecified)error;
- (NSString * _Nullable)shareLinkForFileWithPath:(NSString * _Nonnull)path error:(NSError * _Nullable * _Null_unspecified)error;
- (CRSpaceAllocation * _Nullable)spaceAllocationAndReturnError:(NSError * _Nullable * _Null_unspecified)error;
- (BOOL)loginAndReturnError:(NSError * _Nullable * _Null_unspecified)error;
- (BOOL)logoutAndReturnError:(NSError * _Nullable * _Null_unspecified)error;
- (NSString * _Nullable)saveAsStringAndReturnError:(NSError * _Nullable * _Null_unspecified)error;
- (BOOL)loadAsString:(NSString * _Nonnull)savedState error:(NSError * _Nullable * _Null_unspecified)error;
- (void)setTarget:(id _Null_unspecified)target;
@end


SWIFT_CLASS("_TtC11CloudrailSI12GooglePlaces")
@interface GooglePlaces : NSObject
- (nonnull instancetype)initWithApiKey:(NSString * _Nonnull)apiKey OBJC_DESIGNATED_INITIALIZER;
- (NSMutableArray * _Nullable)nearbyPoisWithLatitude:(double)latitude longitude:(double)longitude radius:(NSInteger)radius searchTerm:(NSString * _Nonnull)searchTerm categories:(NSMutableArray * _Nonnull)categories error:(NSError * _Nullable * _Null_unspecified)error;
- (void)setTarget:(id _Null_unspecified)target;
@end


SWIFT_CLASS("_TtC11CloudrailSI10GooglePlus")
@interface GooglePlus : NSObject
- (nonnull instancetype)initWithClientID:(NSString * _Nonnull)clientID clientSecret:(NSString * _Nonnull)clientSecret redirectUri:(NSString * _Nonnull)redirectUri state:(NSString * _Nonnull)state OBJC_DESIGNATED_INITIALIZER;
- (NSString * _Nullable)identifierAndReturnError:(NSError * _Nullable * _Null_unspecified)error;
- (NSString * _Nullable)fullNameAndReturnError:(NSError * _Nullable * _Null_unspecified)error;
- (NSString * _Nullable)emailAndReturnError:(NSError * _Nullable * _Null_unspecified)error;
- (NSString * _Nullable)genderAndReturnError:(NSError * _Nullable * _Null_unspecified)error;
- (NSString * _Nullable)profileDescriptionAndReturnError:(NSError * _Nullable * _Null_unspecified)error;
- (CRDateOfBirth * _Nullable)dateOfBirthAndReturnError:(NSError * _Nullable * _Null_unspecified)error;
- (NSString * _Nullable)localeAndReturnError:(NSError * _Nullable * _Null_unspecified)error;
- (NSString * _Nullable)pictureURLAndReturnError:(NSError * _Nullable * _Null_unspecified)error;
- (BOOL)loginAndReturnError:(NSError * _Nullable * _Null_unspecified)error;
- (BOOL)logoutAndReturnError:(NSError * _Nullable * _Null_unspecified)error;
- (NSString * _Nullable)saveAsStringAndReturnError:(NSError * _Nullable * _Null_unspecified)error;
- (BOOL)loadAsString:(NSString * _Nonnull)savedState error:(NSError * _Nullable * _Null_unspecified)error;
- (void)setTarget:(id _Null_unspecified)target;
@end


SWIFT_CLASS("_TtC11CloudrailSI9Instagram")
@interface Instagram : NSObject
- (nonnull instancetype)initWithClientID:(NSString * _Nonnull)clientID clientSecret:(NSString * _Nonnull)clientSecret redirectUri:(NSString * _Nonnull)redirectUri state:(NSString * _Nonnull)state OBJC_DESIGNATED_INITIALIZER;
- (NSString * _Nullable)identifierAndReturnError:(NSError * _Nullable * _Null_unspecified)error;
- (NSString * _Nullable)fullNameAndReturnError:(NSError * _Nullable * _Null_unspecified)error;
- (NSString * _Nullable)emailAndReturnError:(NSError * _Nullable * _Null_unspecified)error;
- (NSString * _Nullable)genderAndReturnError:(NSError * _Nullable * _Null_unspecified)error;
- (NSString * _Nullable)profileDescriptionAndReturnError:(NSError * _Nullable * _Null_unspecified)error;
- (CRDateOfBirth * _Nullable)dateOfBirthAndReturnError:(NSError * _Nullable * _Null_unspecified)error;
- (NSString * _Nullable)localeAndReturnError:(NSError * _Nullable * _Null_unspecified)error;
- (NSString * _Nullable)pictureURLAndReturnError:(NSError * _Nullable * _Null_unspecified)error;
- (BOOL)loginAndReturnError:(NSError * _Nullable * _Null_unspecified)error;
- (BOOL)logoutAndReturnError:(NSError * _Nullable * _Null_unspecified)error;
- (NSString * _Nullable)saveAsStringAndReturnError:(NSError * _Nullable * _Null_unspecified)error;
- (BOOL)loadAsString:(NSString * _Nonnull)savedState error:(NSError * _Nullable * _Null_unspecified)error;
- (void)setTarget:(id _Null_unspecified)target;
@end


SWIFT_CLASS("_TtC11CloudrailSI8LinkedIn")
@interface LinkedIn : NSObject
- (nonnull instancetype)initWithClientID:(NSString * _Nonnull)clientID clientSecret:(NSString * _Nonnull)clientSecret redirectUri:(NSString * _Nonnull)redirectUri state:(NSString * _Nonnull)state OBJC_DESIGNATED_INITIALIZER;
- (NSString * _Nullable)identifierAndReturnError:(NSError * _Nullable * _Null_unspecified)error;
- (NSString * _Nullable)fullNameAndReturnError:(NSError * _Nullable * _Null_unspecified)error;
- (NSString * _Nullable)emailAndReturnError:(NSError * _Nullable * _Null_unspecified)error;
- (NSString * _Nullable)genderAndReturnError:(NSError * _Nullable * _Null_unspecified)error;
- (NSString * _Nullable)profileDescriptionAndReturnError:(NSError * _Nullable * _Null_unspecified)error;
- (CRDateOfBirth * _Nullable)dateOfBirthAndReturnError:(NSError * _Nullable * _Null_unspecified)error;
- (NSString * _Nullable)localeAndReturnError:(NSError * _Nullable * _Null_unspecified)error;
- (NSString * _Nullable)pictureURLAndReturnError:(NSError * _Nullable * _Null_unspecified)error;
- (BOOL)loginAndReturnError:(NSError * _Nullable * _Null_unspecified)error;
- (BOOL)logoutAndReturnError:(NSError * _Nullable * _Null_unspecified)error;
- (NSString * _Nullable)saveAsStringAndReturnError:(NSError * _Nullable * _Null_unspecified)error;
- (BOOL)loadAsString:(NSString * _Nonnull)savedState error:(NSError * _Nullable * _Null_unspecified)error;
- (void)setTarget:(id _Null_unspecified)target;
@end


SWIFT_CLASS("_TtC11CloudrailSI7MailJet")
@interface MailJet : NSObject
- (nonnull instancetype)initWithClientID:(NSString * _Nonnull)clientID clientSecret:(NSString * _Nonnull)clientSecret OBJC_DESIGNATED_INITIALIZER;
- (BOOL)sendEmailFromAddress:(NSString * _Nonnull)fromAddress fromName:(NSString * _Nonnull)fromName toAddresses:(NSMutableArray * _Nonnull)toAddresses subject:(NSString * _Nonnull)subject textBody:(NSString * _Nonnull)textBody htmlBody:(NSString * _Nonnull)htmlBody ccAddresses:(NSMutableArray * _Nonnull)ccAddresses bccAddresses:(NSMutableArray * _Nonnull)bccAddresses error:(NSError * _Nullable * _Null_unspecified)error;
- (void)setTarget:(id _Null_unspecified)target;
@end


SWIFT_CLASS("_TtC11CloudrailSI13MicrosoftLive")
@interface MicrosoftLive : NSObject
- (nonnull instancetype)initWithClientID:(NSString * _Nonnull)clientID clientSecret:(NSString * _Nonnull)clientSecret redirectUri:(NSString * _Nonnull)redirectUri state:(NSString * _Nonnull)state OBJC_DESIGNATED_INITIALIZER;
- (NSString * _Nullable)identifierAndReturnError:(NSError * _Nullable * _Null_unspecified)error;
- (NSString * _Nullable)fullNameAndReturnError:(NSError * _Nullable * _Null_unspecified)error;
- (NSString * _Nullable)emailAndReturnError:(NSError * _Nullable * _Null_unspecified)error;
- (NSString * _Nullable)genderAndReturnError:(NSError * _Nullable * _Null_unspecified)error;
- (NSString * _Nullable)profileDescriptionAndReturnError:(NSError * _Nullable * _Null_unspecified)error;
- (CRDateOfBirth * _Nullable)dateOfBirthAndReturnError:(NSError * _Nullable * _Null_unspecified)error;
- (NSString * _Nullable)localeAndReturnError:(NSError * _Nullable * _Null_unspecified)error;
- (NSString * _Nullable)pictureURLAndReturnError:(NSError * _Nullable * _Null_unspecified)error;
- (BOOL)loginAndReturnError:(NSError * _Nullable * _Null_unspecified)error;
- (BOOL)logoutAndReturnError:(NSError * _Nullable * _Null_unspecified)error;
- (NSString * _Nullable)saveAsStringAndReturnError:(NSError * _Nullable * _Null_unspecified)error;
- (BOOL)loadAsString:(NSString * _Nonnull)savedState error:(NSError * _Nullable * _Null_unspecified)error;
- (void)setTarget:(id _Null_unspecified)target;
@end


SWIFT_CLASS("_TtC11CloudrailSI5Nexmo")
@interface Nexmo : NSObject
- (nonnull instancetype)initWithClientID:(NSString * _Nonnull)clientID clientSecret:(NSString * _Nonnull)clientSecret OBJC_DESIGNATED_INITIALIZER;
- (BOOL)sendSmsFromName:(NSString * _Nonnull)fromName toNumber:(NSString * _Nonnull)toNumber content:(NSString * _Nonnull)content error:(NSError * _Nullable * _Null_unspecified)error;
- (void)setTarget:(id _Null_unspecified)target;
@end


SWIFT_CLASS("_TtC11CloudrailSI8OneDrive")
@interface OneDrive : NSObject
- (nonnull instancetype)initWithClientID:(NSString * _Nonnull)clientID clientSecret:(NSString * _Nonnull)clientSecret redirectUri:(NSString * _Nonnull)redirectUri state:(NSString * _Nonnull)state OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithClientId:(NSString * _Nonnull)clientId clientSecret:(NSString * _Nonnull)clientSecret OBJC_DESIGNATED_INITIALIZER;
- (NSInputStream * _Nullable)downloadFileWithPath:(NSString * _Nonnull)filePath error:(NSError * _Nullable * _Null_unspecified)error;
- (BOOL)uploadFileToPath:(NSString * _Nonnull)filePath stream:(NSInputStream * _Nonnull)stream size:(long)size overwrite:(BOOL)overwrite error:(NSError * _Nullable * _Null_unspecified)error;
- (BOOL)moveFileFromPath:(NSString * _Nonnull)sourcePath destinationPath:(NSString * _Nonnull)destinationPath error:(NSError * _Nullable * _Null_unspecified)error;
- (BOOL)deleteFileWithPath:(NSString * _Nonnull)filePath error:(NSError * _Nullable * _Null_unspecified)error;
- (BOOL)copyFileFromPath:(NSString * _Nonnull)sourcePath destinationPath:(NSString * _Nonnull)destinationPath error:(NSError * _Nullable * _Null_unspecified)error;
- (BOOL)createFolderWithPath:(NSString * _Nonnull)folderPath error:(NSError * _Nullable * _Null_unspecified)error;
- (CRCloudMetaData * _Nullable)metadataOfFileWithPath:(NSString * _Nonnull)filePath error:(NSError * _Nullable * _Null_unspecified)error;
- (NSMutableArray * _Nullable)childrenOfFolderWithPath:(NSString * _Nonnull)folderPath error:(NSError * _Nullable * _Null_unspecified)error;
- (NSString * _Nullable)userLoginAndReturnError:(NSError * _Nullable * _Null_unspecified)error;
- (NSString * _Nullable)userNameAndReturnError:(NSError * _Nullable * _Null_unspecified)error;
- (NSString * _Nullable)shareLinkForFileWithPath:(NSString * _Nonnull)path error:(NSError * _Nullable * _Null_unspecified)error;
- (CRSpaceAllocation * _Nullable)spaceAllocationAndReturnError:(NSError * _Nullable * _Null_unspecified)error;
- (BOOL)loginAndReturnError:(NSError * _Nullable * _Null_unspecified)error;
- (BOOL)logoutAndReturnError:(NSError * _Nullable * _Null_unspecified)error;
- (NSString * _Nullable)saveAsStringAndReturnError:(NSError * _Nullable * _Null_unspecified)error;
- (BOOL)loadAsString:(NSString * _Nonnull)savedState error:(NSError * _Nullable * _Null_unspecified)error;
- (void)setTarget:(id _Null_unspecified)target;
@end

@class CRCreditCard;
@class CRCharge;
@class CRRefund;
@class CRSubscriptionPlan;
@class CRSubscription;

SWIFT_CLASS("_TtC11CloudrailSI6PayPal")
@interface PayPal : NSObject
- (nonnull instancetype)initWithUseSandbox:(BOOL)useSandbox clientId:(NSString * _Nonnull)clientId clientSecret:(NSString * _Nonnull)clientSecret OBJC_DESIGNATED_INITIALIZER;
- (CRCharge * _Nullable)createChargeWithAmount:(NSInteger)amount currency:(NSString * _Nonnull)currency source:(CRCreditCard * _Nonnull)source error:(NSError * _Nullable * _Null_unspecified)error;
- (CRCharge * _Nullable)chargeWithIdentifier:(NSString * _Nonnull)id error:(NSError * _Nullable * _Null_unspecified)error;
- (NSMutableArray * _Nullable)listChargesFrom:(NSInteger)from to:(NSInteger)to creditCard:(CRCreditCard * _Nonnull)creditCard error:(NSError * _Nullable * _Null_unspecified)error;
- (CRRefund * _Nullable)refundChargeWithIdentifier:(NSString * _Nonnull)id error:(NSError * _Nullable * _Null_unspecified)error;
- (CRRefund * _Nullable)partiallyRefundChargeWithIdentifier:(NSString * _Nonnull)id amount:(NSInteger)amount error:(NSError * _Nullable * _Null_unspecified)error;
- (CRRefund * _Nullable)refundWithIdentifier:(NSString * _Nonnull)id error:(NSError * _Nullable * _Null_unspecified)error;
- (NSMutableArray * _Nullable)refundsForChargeWithIdentifier:(NSString * _Nonnull)id error:(NSError * _Nullable * _Null_unspecified)error;
- (CRSubscriptionPlan * _Nullable)createSubscriptionPlanWithName:(NSString * _Nonnull)name amount:(NSInteger)amount currency:(NSString * _Nonnull)currency description:(NSString * _Nonnull)description interval:(NSString * _Nonnull)interval intervalCount:(NSInteger)intervalCount error:(NSError * _Nullable * _Null_unspecified)error;
- (NSMutableArray * _Nullable)listSubscriptionPlansAndReturnError:(NSError * _Nullable * _Null_unspecified)error;
- (CRSubscription * _Nullable)createSubscriptionWithPlanID:(NSString * _Nonnull)planID name:(NSString * _Nonnull)name description:(NSString * _Nonnull)description source:(CRCreditCard * _Nonnull)source error:(NSError * _Nullable * _Null_unspecified)error;
- (BOOL)cancelSubscriptionWithIdentifier:(NSString * _Nonnull)id error:(NSError * _Nullable * _Null_unspecified)error;
- (void)setTarget:(id _Null_unspecified)target;
@end


SWIFT_CLASS("_TtC11CloudrailSI8SendGrid")
@interface SendGrid : NSObject
- (nonnull instancetype)initWithApiKey:(NSString * _Nonnull)apiKey OBJC_DESIGNATED_INITIALIZER;
- (BOOL)sendEmailFromAddress:(NSString * _Nonnull)fromAddress fromName:(NSString * _Nonnull)fromName toAddresses:(NSMutableArray * _Nonnull)toAddresses subject:(NSString * _Nonnull)subject textBody:(NSString * _Nonnull)textBody htmlBody:(NSString * _Nonnull)htmlBody ccAddresses:(NSMutableArray * _Nonnull)ccAddresses bccAddresses:(NSMutableArray * _Nonnull)bccAddresses error:(NSError * _Nullable * _Null_unspecified)error;
- (void)setTarget:(id _Null_unspecified)target;
@end


SWIFT_CLASS("_TtC11CloudrailSI5Slack")
@interface Slack : NSObject
- (nonnull instancetype)initWithClientId:(NSString * _Nonnull)clientId clientSecret:(NSString * _Nonnull)clientSecret redirectUri:(NSString * _Nonnull)redirectUri state:(NSString * _Nonnull)state OBJC_DESIGNATED_INITIALIZER;
- (NSString * _Nullable)identifierAndReturnError:(NSError * _Nullable * _Null_unspecified)error;
- (NSString * _Nullable)fullNameAndReturnError:(NSError * _Nullable * _Null_unspecified)error;
- (NSString * _Nullable)emailAndReturnError:(NSError * _Nullable * _Null_unspecified)error;
- (NSString * _Nullable)genderAndReturnError:(NSError * _Nullable * _Null_unspecified)error;
- (NSString * _Nullable)profileDescriptionAndReturnError:(NSError * _Nullable * _Null_unspecified)error;
- (CRDateOfBirth * _Nullable)dateOfBirthAndReturnError:(NSError * _Nullable * _Null_unspecified)error;
- (NSString * _Nullable)localeAndReturnError:(NSError * _Nullable * _Null_unspecified)error;
- (NSString * _Nullable)pictureURLAndReturnError:(NSError * _Nullable * _Null_unspecified)error;
- (BOOL)loginAndReturnError:(NSError * _Nullable * _Null_unspecified)error;
- (BOOL)logoutAndReturnError:(NSError * _Nullable * _Null_unspecified)error;
- (NSString * _Nullable)saveAsStringAndReturnError:(NSError * _Nullable * _Null_unspecified)error;
- (BOOL)loadAsString:(NSString * _Nonnull)savedState error:(NSError * _Nullable * _Null_unspecified)error;
- (void)setTarget:(id _Null_unspecified)target;
@end


SWIFT_CLASS("_TtC11CloudrailSI6Stripe")
@interface Stripe : NSObject
- (nonnull instancetype)initWithSecretKey:(NSString * _Nonnull)secretKey OBJC_DESIGNATED_INITIALIZER;
- (CRCharge * _Nullable)createChargeWithAmount:(NSInteger)amount currency:(NSString * _Nonnull)currency source:(CRCreditCard * _Nonnull)source error:(NSError * _Nullable * _Null_unspecified)error;
- (CRCharge * _Nullable)chargeWithIdentifier:(NSString * _Nonnull)id error:(NSError * _Nullable * _Null_unspecified)error;
- (NSMutableArray * _Nullable)listChargesFrom:(NSInteger)from to:(NSInteger)to creditCard:(CRCreditCard * _Nonnull)creditCard error:(NSError * _Nullable * _Null_unspecified)error;
- (CRRefund * _Nullable)refundChargeWithIdentifier:(NSString * _Nonnull)id error:(NSError * _Nullable * _Null_unspecified)error;
- (CRRefund * _Nullable)partiallyRefundChargeWithIdentifier:(NSString * _Nonnull)id amount:(NSInteger)amount error:(NSError * _Nullable * _Null_unspecified)error;
- (CRRefund * _Nullable)refundWithIdentifier:(NSString * _Nonnull)id error:(NSError * _Nullable * _Null_unspecified)error;
- (NSMutableArray * _Nullable)refundsForChargeWithIdentifier:(NSString * _Nonnull)id error:(NSError * _Nullable * _Null_unspecified)error;
- (CRSubscriptionPlan * _Nullable)createSubscriptionPlanWithName:(NSString * _Nonnull)name amount:(NSInteger)amount currency:(NSString * _Nonnull)currency description:(NSString * _Nonnull)description interval:(NSString * _Nonnull)interval intervalCount:(NSInteger)intervalCount error:(NSError * _Nullable * _Null_unspecified)error;
- (NSMutableArray * _Nullable)listSubscriptionPlansAndReturnError:(NSError * _Nullable * _Null_unspecified)error;
- (CRSubscription * _Nullable)createSubscriptionWithPlanID:(NSString * _Nonnull)planID name:(NSString * _Nonnull)name description:(NSString * _Nonnull)description source:(CRCreditCard * _Nonnull)source error:(NSError * _Nullable * _Null_unspecified)error;
- (BOOL)cancelSubscriptionWithIdentifier:(NSString * _Nonnull)id error:(NSError * _Nullable * _Null_unspecified)error;
- (void)setTarget:(id _Null_unspecified)target;
@end


SWIFT_CLASS("_TtC11CloudrailSI6Twilio")
@interface Twilio : NSObject
- (nonnull instancetype)initWithAccountSid:(NSString * _Nonnull)accountSid authToken:(NSString * _Nonnull)authToken OBJC_DESIGNATED_INITIALIZER;
- (BOOL)sendSmsFromName:(NSString * _Nonnull)fromName toNumber:(NSString * _Nonnull)toNumber content:(NSString * _Nonnull)content error:(NSError * _Nullable * _Null_unspecified)error;
- (void)setTarget:(id _Null_unspecified)target;
@end


SWIFT_CLASS("_TtC11CloudrailSI7Twitter")
@interface Twitter : NSObject
- (nonnull instancetype)initWithClientID:(NSString * _Nonnull)clientID clientSecret:(NSString * _Nonnull)clientSecret redirectUri:(NSString * _Nonnull)redirectUri OBJC_DESIGNATED_INITIALIZER;
- (NSString * _Nullable)identifierAndReturnError:(NSError * _Nullable * _Null_unspecified)error;
- (NSString * _Nullable)fullNameAndReturnError:(NSError * _Nullable * _Null_unspecified)error;
- (NSString * _Nullable)emailAndReturnError:(NSError * _Nullable * _Null_unspecified)error;
- (NSString * _Nullable)genderAndReturnError:(NSError * _Nullable * _Null_unspecified)error;
- (NSString * _Nullable)profileDescriptionAndReturnError:(NSError * _Nullable * _Null_unspecified)error;
- (CRDateOfBirth * _Nullable)dateOfBirthAndReturnError:(NSError * _Nullable * _Null_unspecified)error;
- (NSString * _Nullable)localeAndReturnError:(NSError * _Nullable * _Null_unspecified)error;
- (NSString * _Nullable)pictureURLAndReturnError:(NSError * _Nullable * _Null_unspecified)error;
- (BOOL)loginAndReturnError:(NSError * _Nullable * _Null_unspecified)error;
- (BOOL)logoutAndReturnError:(NSError * _Nullable * _Null_unspecified)error;
- (BOOL)postUpdateWithContent:(NSString * _Nonnull)content error:(NSError * _Nullable * _Null_unspecified)error;
- (NSMutableArray * _Nullable)connectionsAndReturnError:(NSError * _Nullable * _Null_unspecified)error;
- (NSString * _Nullable)saveAsStringAndReturnError:(NSError * _Nullable * _Null_unspecified)error;
- (BOOL)loadAsString:(NSString * _Nonnull)savedState error:(NSError * _Nullable * _Null_unspecified)error;
- (void)setTarget:(id _Null_unspecified)target;
@end


SWIFT_CLASS("_TtC11CloudrailSI5Yahoo")
@interface Yahoo : NSObject
- (nonnull instancetype)initWithClientId:(NSString * _Nonnull)clientId clientSecret:(NSString * _Nonnull)clientSecret redirectUri:(NSString * _Nonnull)redirectUri state:(NSString * _Nonnull)state OBJC_DESIGNATED_INITIALIZER;
- (NSString * _Nullable)identifierAndReturnError:(NSError * _Nullable * _Null_unspecified)error;
- (NSString * _Nullable)fullNameAndReturnError:(NSError * _Nullable * _Null_unspecified)error;
- (NSString * _Nullable)emailAndReturnError:(NSError * _Nullable * _Null_unspecified)error;
- (NSString * _Nullable)genderAndReturnError:(NSError * _Nullable * _Null_unspecified)error;
- (NSString * _Nullable)profileDescriptionAndReturnError:(NSError * _Nullable * _Null_unspecified)error;
- (CRDateOfBirth * _Nullable)dateOfBirthAndReturnError:(NSError * _Nullable * _Null_unspecified)error;
- (NSString * _Nullable)localeAndReturnError:(NSError * _Nullable * _Null_unspecified)error;
- (NSString * _Nullable)pictureURLAndReturnError:(NSError * _Nullable * _Null_unspecified)error;
- (BOOL)loginAndReturnError:(NSError * _Nullable * _Null_unspecified)error;
- (BOOL)logoutAndReturnError:(NSError * _Nullable * _Null_unspecified)error;
- (NSString * _Nullable)saveAsStringAndReturnError:(NSError * _Nullable * _Null_unspecified)error;
- (BOOL)loadAsString:(NSString * _Nonnull)savedState error:(NSError * _Nullable * _Null_unspecified)error;
- (void)setTarget:(id _Null_unspecified)target;
@end


SWIFT_CLASS("_TtC11CloudrailSI4Yelp")
@interface Yelp : NSObject
- (nonnull instancetype)initWithConsumerKey:(NSString * _Nonnull)consumerKey consumerSecret:(NSString * _Nonnull)consumerSecret token:(NSString * _Nonnull)token tokenSecret:(NSString * _Nonnull)tokenSecret OBJC_DESIGNATED_INITIALIZER;
- (NSMutableArray * _Nullable)nearbyPoisWithLatitude:(double)latitude longitude:(double)longitude radius:(NSInteger)radius searchTerm:(NSString * _Nonnull)searchTerm categories:(NSMutableArray * _Nonnull)categories error:(NSError * _Nullable * _Null_unspecified)error;
- (void)setTarget:(id _Null_unspecified)target;
@end

#pragma clang diagnostic pop
